name: Workflow
  
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build
      run: mvn --batch-mode --update-snapshots verify

    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v3.0.0

    - name: Docker Setup Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: Dockerfile
        platforms: linux/amd64, linux/arm64/v8
        push: true
        tags: |
          alexholanda/financeiro-api:latest
          alexholanda/financeiro-api:${{ github.sha }}

  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Mudando para o repositório de deployment
        uses: actions/checkout@v4
        with:
          repository: 'alex-holanda/perfilnet-apigateway-cd'
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}
      - name: Modificando a imagem
        run: |
          cd helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml

          git config --global user.name 'Alex Holanda'
          git config --global user.email 'alex.holanda@outlook.com'

          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.sha }}'
          git push origin main
        env:
          RUN_NUMBER: ${{ github.sha }}